version: ~> 1.0 # needed for imports

import: scala/scala-dev:travis/default.yml

language: scala

scala:
  - 2.11.12
  - 2.12.11
  - 2.13.3
  - 3.0.0-RC2

env:
  - ADOPTOPENJDK=8
  - ADOPTOPENJDK=11

install:
  - git fetch --tags # get all tags for sbt-dynver

script: ./build.sh

notifications:
  email:
    - seth.tisue@lightbend.com
    - andy@hicks.net
